### ISSUE TITLE
nodemon server

### ISSUE THREAD

**Issue by marcalbet** [KrunalLathiya/Angular7CRUDExample#1]
I've installed nodemon but when I run nodemon server I have an error about nodemon is not recognized.

How can I run nodemon server? I have installed MongoDB.

**Comment by mseradzenka** [comment]
> I've installed nodemon but when I run nodemon server I have an error about nodemon is not recognized.
> 
> How can I run nodemon server? I have installed MongoDB.

 Faced the same problem. Try to add launching script into package.json, something like:
"start": "nodemon server.js"

**Comment by marcalbet** [comment]
Hi,

I did it, but I still have the same problem.

**Comment by marcalbet** [comment]
Finally I solved it installing nodemon globally like this:

`npm install -g nodemon`

or with permission
`npm install -g nodemon`

or if using yarn
`yarn global add nodemon`

---
For checking if nodemon exists or not:
`nodemon -v`
